language: node_js

node_js:
  - '12'

install:
  - npm install --save-dev jest

script:
  - jest --coverage

cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'

after_success:
  - bash <(curl -s https://codecov.io/bash)
